#!/bin/sh
#
# Set up any hardware/platform stuff.
#

LOG_TTY=tty2

start() {
	# First, let's start tailing the system log on a tty, to make things easier to support
	# when things go wrong.
	setsid tail -f /var/log/messages > /dev/$LOG_TTY < /dev/$LOG_TTY 2>&1 &

	# Call an LED event hook
	/bin/led-event start-boot

	printf "Loading platform drivers and mounting filesystems: "
	# Load drivers for specific generic layers (ie, block drivers) that sit
	# atop hardware-specific drivers.
	modprobe -a virtio_blk usb_storage sd_mod 2>/dev/null

	# Load any PCI or USB devices we can. We could add other bus types later
	for bus in pci usb
	do
		for i in /sys/bus/$bus/devices/*
		do
			# Read the uevent file from sysfs and load the driver
			# by alias.
			MODALIAS=""
			. $i/uevent
			[ -z "$MODALIAS" ] || modprobe "$MODALIAS" 2>/dev/null
		done
	done
	mkdir -p /var/lib/docker
	mount -a
	echo "OK"

}

stop() {
	printf "Shutting down platform: "
	# Take a backup of the log files stored in the tmpfs for supportability
	(
		cd /var/log
		mkdir /var/last-boot
		for i in *
		do
			gzip -c9 $i > /var/last-boot/$i.gz
		done
	)
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 (start|stop|restart)"
		exit 1
esac
