#!/bin/sh
#
# Perform any earlier platform configuration
#

start() {
	printf "Loading configuration: "
	/usr/bin/holos-config -s configure
	# we should probably check the return value here later.
	echo "OK"
}

stop() {
	# We don't currently have anything we need to do here, but may later.
	printf "Stopping config: "
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 (start|stop|restart)"
		exit 1
esac
