FROM ghcr.io/holo-host/edgenode:latest-hc0.6.0-go-pion-dev

RUN wget https://github.com/Holo-Host/log-sender/releases/download/v0.1.0p3/log-sender && \
    mv log-sender /bin/log-sender && \
    chmod +x /bin/log-sender

COPY log_tool /usr/local/bin/log_tool
RUN chmod +x /usr/local/bin/log_tool

SHELL ["/bin/sh", "-c"]
EXPOSE 4444

# Set entrypoint to keep container running and allow interactive shell access
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]