FROM local-edgenode-hc-0.6.0-dev-go-pion

RUN wget https://github.com/unytco/log-sender/releases/download/v0.1.4/log-sender && \
    mv log-sender /usr/local/bin/log-sender && \
    chmod +x /usr/local/bin/log-sender && \
    mkdir -p /etc/log-sender && \
    chown nonroot:nonroot /etc/log-sender

COPY log_tool /usr/local/bin/log_tool
RUN chmod +x /usr/local/bin/log_tool

SHELL ["/bin/sh", "-c"]
EXPOSE 4444