[supervisord]
nodaemon=true
logfile=/data/logs/supervisord.log
[program:holochain]
command=sh -c 'RUST_LOG=${RUST_LOG:-debug} holochain --piped --config-path /etc/holochain/conductor-config.yaml'
user=nonroot
stdout_logfile=/data/logs/holochain.log
stderr_logfile=/data/logs/holochain.err
autorestart=true
