[supervisord]
nodaemon=true

[program:holochain]
command=sh -c 'gosu nonroot holochain --piped --config-path /etc/holochain/conductor-config.yaml'
stdout_logfile=/data/logs/holochain.log
stderr_logfile=/data/logs/holochain.err
autorestart=true

[program:log-sender]
command=log-sender service --config-file /etc/log-sender/config.json
stdout_logfile=/data/logs/log-sender.log
stderr_logfile=/data/logs/log-sender.err
autorestart=true