SYSBOX_RUNTIME_VERSION = v0.6.7
SYSBOX_RUNTIME_SITE = git://github.com/nestybox/sysbox 
SYSBOX_RUNTIME_LICENSE = MIT
SYSBOX_RUNTIME_LICENSE_FILE = LICENSE

define SYSBOX_RUNTIME_BUILD_CMDS
	$(MAKE)
endef

define SYSBOX_RUNTIME_INSTALL_TARGET_CMDS
	$(MAKE) install INSTALL_DIR=$(TARGET_DIR)
endef

$(eval $(generic-package))
